/* THROWAWAY - capability and remote-access UI exploration. All state stays in page memory. */
function initializeCapabilities(){
  state.capabilityType='skill';
  state.capabilities={
    skill:[
      {name:'project-deep-dive-interview',description:'从候选人材料生成项目深挖面试手册',source:'全局 · ~/.agents/skills',scope:'所有项目',enabled:true,status:'可用',risk:'读取所选材料'},
      {name:'buf-cli',description:'检查和维护 Protocol Buffers 工作流',source:'全局 · ~/.agents/skills',scope:'所有项目',enabled:true,status:'可用',risk:'按会话权限调用命令'},
      {name:'release-check',description:'当前项目的交付检查清单',source:'项目 · .pi/skills',scope:'Adber',enabled:false,status:'检测到',risk:'读取项目文件'}
    ],
    mcp:[
      {name:'Linear',description:'查询和更新团队工单',source:'Extension 桥接 · stdio',scope:'所有项目',enabled:true,status:'已连接',risk:'外部读写 · 使用本机凭据'},
      {name:'PostgreSQL · 测试库',description:'只读查询测试环境数据',source:'Extension 桥接 · stdio',scope:'Adber',enabled:false,status:'未连接',risk:'外部读取 · 含敏感数据'}
    ],
    extension:[
      {name:'mcp-bridge',description:'把已配置的 MCP Server 暴露为 pi 工具',source:'全局 · ~/.pi/agent/extensions',scope:'所有项目',enabled:true,status:'已加载',risk:'注册工具 · 启动子进程'},
      {name:'workspace-guard',description:'在工具调用前校验任务路径与执行权',source:'PiDock 内置',scope:'所有任务',enabled:true,status:'已加载',risk:'拦截工具调用'},
      {name:'team-commands',description:'提供团队斜杠命令和提示模板',source:'项目 · .pi/extensions',scope:'Adber',enabled:false,status:'待重载',risk:'注册命令 · 可调用工具'}
    ],
    package:[
      {name:'@team/pi-toolkit',description:'包含 2 个 Skills 和 1 个 Extension',source:'npm · 2.4.1（固定）',scope:'所有项目',enabled:true,status:'已安装',risk:'安装与执行第三方代码'},
      {name:'git:company/pi-adber',description:'Adber 项目命令与交付检查',source:'git · 8f31c2a（固定）',scope:'Adber',enabled:true,status:'可更新',risk:'包含项目 Extension'}
    ]
  };
  state.remote={mode:'tailscale',connected:false,gatewayUrl:'https://remote.example.com',tailscaleUrl:'https://leon-mac.example-tailnet.ts.net',funnelUrl:'https://leon-mac.example-tailnet.ts.net',workspaceName:'Leon 的 MacBook',pairVersion:1,permissions:{overview:true,chat:true,manage:true,files:false,terminal:false},devices:[{name:'iPhone 15 Pro',detail:'Safari · 上海 · 2 分钟前',current:true},{name:'iPad',detail:'Safari · 14 天前',current:false}]};
}

function capabilityNavigation(){return `<button class="navbtn ${state.view==='schedules'?'active':''}" data-action="view:schedules" title="定时任务">${icon('clock')}<span class="navtext">定时任务</span></button><button class="navbtn ${state.view==='capabilities'?'active':''}" data-action="view:capabilities" title="能力管理">${icon('book')}<span class="navtext">能力管理</span></button><button class="navbtn ${state.view==='remote'?'active':''}" data-action="view:remote" title="远程访问">${icon('globe')}<span class="navtext">远程访问</span></button>`}
const capabilityLabels={skill:'Skills',mcp:'MCP Servers',extension:'Extensions',package:'Packages'};
function capabilityCounts(type){const rows=state.capabilities[type];return `${rows.filter(x=>x.enabled).length} / ${rows.length} 已启用`}
function capabilitiesPage(){const type=state.capabilityType,rows=state.capabilities[type];const addLabel={skill:'添加技能来源',mcp:'添加 MCP Server',extension:'添加 Extension',package:'安装扩展包'}[type];return `<div class="page capability-page"><div class="between rowgap"><div><div class="view-label">AGENT CAPABILITIES</div><h1>能力管理</h1></div>${button(addLabel,'add-capability:'+type,'primary','plus')}</div><p class="page-intro">Package 负责安装与版本，Skill、MCP 和 Extension 分别展示运行来源、作用域与风险。</p><div class="capability-summary"><div><strong>${state.capabilities.skill.length}</strong><small>Skills</small></div><div><strong>${state.capabilities.mcp.length}</strong><small>MCP Servers</small></div><div><strong>${state.capabilities.extension.length}</strong><small>Extensions</small></div><div><strong>${state.capabilities.package.length}</strong><small>Packages</small></div></div><div class="tabs capability-tabs">${Object.entries(capabilityLabels).map(([key,label])=>`<button class="${type===key?'active':''}" data-action="capability-type:${key}">${label}<span>${capabilityCounts(key)}</span></button>`).join('')}</div>${type==='mcp'?'<div class="inline-notice">Pi 原生不包含 MCP。PiDock 管理 Server，并通过受控的桥接 Extension 注册工具；首版不承诺兼容 MCP 的 prompts、resources 等其他能力。</div>':type==='package'?'<div class="inline-notice">Package 是 npm、git 或本地来源的安装与更新单元；其中可包含多个 Skills、Extensions、Prompts 或主题。</div>':''}<div class="capability-list">${rows.map((item,i)=>capabilityRow(item,i,type)).join('')}</div><div class="note">启停只改变页面内存。正式产品需要区分配置已保存、包已安装与运行时已加载，并在会话空闲边界重载。</div></div>`}
function capabilityRow(item,index,type){return `<div class="capability-row"><button class="capability-main" data-action="capability-detail:${type}:${index}"><span class="capability-icon">${icon(type==='skill'?'book':type==='mcp'?'server':type==='package'?'archive':'code')}</span><span><strong>${esc(item.name)}</strong><small>${esc(item.description)}</small><span class="capability-meta"><span>${esc(item.source)}</span><span>${esc(item.scope)}</span><span>${esc(item.risk)}</span></span></span></button><span class="badge ${item.status.includes('已')||item.status==='可用'?'live':item.status.includes('待')||item.status.includes('更新')?'warn':''}">${esc(item.status)}</span><label class="switch-control" title="${item.enabled?'停用':'启用'} ${esc(item.name)}"><input type="checkbox" data-capability-toggle="${type}:${index}" ${item.enabled?'checked':''}><span></span></label></div>`}
function capabilityDetail(type,index){const item=state.capabilities[type]?.[index];if(!item)return;const boundary=type==='skill'?'技能提供按需加载的指引；其中脚本和实际工具调用继续遵循会话权限。':type==='mcp'?'MCP Server 由 PiDock 管理，并通过桥接 Extension 提供工具；连接凭据与项目共享配置分开保存。':type==='package'?'Package 是安装与更新单元；启用前需要审阅固定版本、所含资源及可执行代码。':'Extension 与 Pi 进程拥有相同系统权限，可注册工具、命令和事件处理器；启用前需要审阅来源。';modal(item.name,`<div class="capability-detail"><div class="detail-grid"><span>类型</span><strong>${capabilityLabels[type]}</strong><span>来源</span><code>${esc(item.source)}</code><span>作用域</span><strong>${esc(item.scope)}</strong><span>状态</span><strong>${esc(item.status)}</strong></div><div class="inline-notice">${boundary}</div><h3>声明的能力</h3><p class="page-intro">${esc(item.risk)}</p><div class="preview-note">来源内容、配置和权限均为原型示例，尚未读取、安装或执行真实资源。</div></div>`,button(item.enabled?'停用':'启用','toggle-capability:'+type+':'+index,item.enabled?'danger':'primary'))}
function addCapabilityDialog(type){const labels={skill:['添加技能来源','目录路径','例如 ~/.agents/skills'],mcp:['添加 MCP Server','启动命令或远程地址','例如 npx @example/mcp-server'],extension:['添加 Extension','文件路径','例如 ~/.pi/agent/extensions/team.ts'],package:['安装扩展包','npm、git 或本地来源','例如 npm:@team/pi-toolkit@2.4.1']}[type];modal(labels[0],`<div class="formfield"><label>名称</label><input id="capability-name" placeholder="便于识别的名称"></div><div class="formfield"><label>${labels[1]}</label><input id="capability-source" placeholder="${labels[2]}"></div><div class="formfield"><label>作用域</label><select id="capability-scope"><option>仅当前项目</option><option>所有项目</option></select></div><div class="inline-notice">${type==='package'?'先解析固定版本和资源清单，等待本机确认后才安装。':'添加后先保持停用，审阅来源与权限后再显式启用。'}</div>`,button(type==='package'?'添加到待安装':'添加为停用','save-capability:'+type,'primary'))}

const remoteModes={tailscale:{label:'Tailscale 私有访问',hint:'推荐个人与小团队'},gateway:{label:'自建 Gateway',hint:'普通浏览器访问'},funnel:{label:'Funnel',hint:'实验性公网入口'}};
function remoteBaseUrl(){const r=state.remote;return r.mode==='gateway'?r.gatewayUrl:r.mode==='funnel'?r.funnelUrl:r.tailscaleUrl}
function remoteConnectionPanel(){const r=state.remote;if(r.mode==='tailscale')return `<div class="inline-notice remote-mode-note"><strong>手机需安装并连接 Tailscale</strong><span>PiDock Host 仅监听 127.0.0.1，由 Serve 在 tailnet 内提供 HTTPS。</span></div><div class="connection-checks"><div><span class="dot"></span><span><strong>本机 Tailscale</strong><small>原型示例：未检测到可用安装</small></span>${button('重新检测','remote-detect','sm')}</div><div><span class="dot live"></span><span><strong>Serve 地址</strong><small class="mono">${esc(r.tailscaleUrl)}</small></span></div><div><span class="dot live"></span><span><strong>访问策略</strong><small>仅允许指定用户访问 tcp:443</small></span></div></div><div class="command-preview"><code>tailscale serve --bg 127.0.0.1:4318</code></div>`;if(r.mode==='funnel')return `<div class="inline-notice remote-mode-note warn"><strong>公网实验入口</strong><span>无需手机安装 Tailscale，但 URL 对互联网公开；PiDock 必须自行登录、授权、限流与审计。</span></div><div class="formfield"><label>Funnel 地址</label><input id="remote-url" value="${esc(r.funnelUrl)}"></div><div class="command-preview"><code>tailscale funnel --bg 127.0.0.1:4318</code></div>`;return `<div class="formfield"><label>PiDock Gateway 地址</label><input id="remote-url" value="${esc(r.gatewayUrl)}" placeholder="https://remote.example.com"></div><div class="remote-flow"><span>手机浏览器</span>${icon('right')}<span>自建 Gateway</span>${icon('right')}<span>本机 PiDock</span></div><div class="gateway-details"><span>HTTPS / WSS</span><span>桌面主动连接</span><span>设备凭据可轮换</span></div>`}
function remoteAccessPage(){const r=state.remote;return `<div class="page remote-page"><div class="between rowgap"><div><div class="view-label">REMOTE ACCESS</div><h1>远程访问</h1></div><div class="flex"><span class="badge ${r.connected?'live':''}">${r.connected?'远程入口已连接':'尚未连接'}</span>${button('手机视图','remote-preview','','globe')}</div></div><p class="page-intro">选择私有网络、自建 Gateway 或实验性公网入口；三种模式共享同一套设备授权和 PiDock 领域权限。</p><div class="remote-mode-picker">${Object.entries(remoteModes).map(([key,m])=>`<button class="${r.mode===key?'selected':''}" data-action="remote-mode:${key}"><span>${icon(key==='tailscale'?'shield':key==='gateway'?'server':'globe')}</span><strong>${m.label}</strong><small>${m.hint}</small>${key==='tailscale'?'<em>推荐</em>':''}</button>`).join('')}</div><div class="remote-layout"><section><div class="card remote-connection"><div class="between"><div><h3>${remoteModes[r.mode].label}</h3><small>${r.connected?'最近心跳：刚刚':'配置后可模拟连接'}</small></div><span class="status-orb ${r.connected?'connected':''}"></span></div><div class="formfield toolbar-space"><label>这台电脑的名称</label><input id="remote-workspace-name" value="${esc(r.workspaceName)}"></div>${remoteConnectionPanel()}<div class="between toolbar-space"><small>${r.mode==='gateway'?'TLS · 出站 WSS · 不开放本机端口':r.mode==='tailscale'?'Tailnet 私有 HTTPS · 无需 Relay URL':'公网 HTTPS · 高风险操作仍需本机确认'}</small>${button(r.connected?'断开连接':'启用此入口','toggle-remote',r.connected?'':'primary',r.connected?'stop':'play')}</div></div><div class="card"><div class="between"><h3>移动端允许的操作</h3><span class="badge">设备级授权</span></div><div class="permission-list">${remotePermission('overview','查看项目、任务和运行状态','只读')}${remotePermission('chat','查看对话并发送消息','消息会进入原会话')}${remotePermission('manage','暂停任务、归档与启停服务','每次敏感操作再次确认')}${remotePermission('files','查看文件和差异','默认关闭')}${remotePermission('terminal','远程终端','高风险 · 默认关闭')}</div></div></section><aside><div class="card"><div class="between"><h3>已授权设备</h3>${button('扫码添加','pair-device','sm primary','plus')}</div><small>生成短时、单次使用的配对链接；扫码后仍需本机确认。</small><div class="device-list">${r.devices.map((d,i)=>`<div class="device-row"><span class="device-symbol">${icon('globe')}</span><span><strong>${esc(d.name)}</strong><small>${esc(d.detail)}</small></span>${d.current?'<span class="badge live">当前</span>':button('撤销','revoke-device:'+i,'sm danger')}</div>`).join('')}</div></div><div class="card remote-guard"><h3>远程操作仍受本机约束</h3><p>会话权限、任务执行权、共享模板确认和浏览器接管规则不因远程访问放宽。</p><p>二维码不含长期凭据；过期、使用或手动刷新后立即失效。</p></div></aside></div></div>`}
function remotePermission(key,title,detail){const checked=state.remote.permissions[key];return `<label><input type="checkbox" data-remote-permission="${key}" ${checked?'checked':''}><span><strong>${title}</strong><small>${detail}</small></span></label>`}
function pairingCode(){return `PW7K-${String(4200+state.remote.pairVersion).padStart(4,'0')}`}
function pairingUrl(){const base=remoteBaseUrl().replace(/\/$/,'');return `${base}/pair#token=demo-${state.remote.pairVersion}-${pairingCode().replace('-','')}`}
function drawPairingQr(){const target=document.querySelector('#pair-qr');if(!target)return;if(typeof qrcode!=='function'){target.innerHTML='<div class="qr-fallback">二维码组件未加载<br>请使用下方链接</div>';return}const qr=qrcode(0,'M');qr.addData(pairingUrl());qr.make();target.innerHTML=qr.createSvgTag({cellSize:5,margin:2,scalable:true})}
function pairDeviceDialog(){const mode=remoteModes[state.remote.mode].label;modal('扫码添加移动设备',`<div class="pairing-layout"><div id="pair-qr" class="pair-qr" aria-label="配对二维码"></div><div><div class="pair-code"><span>一次性配对码</span><strong>${esc(pairingCode())}</strong><small>10 分钟内有效 · 使用一次后失效</small></div><p class="pair-mode">${esc(mode)}</p><a class="pair-link" href="${esc(pairingUrl())}" target="_blank" rel="noreferrer">${esc(pairingUrl())}</a></div></div><div class="help-list"><p>1. 手机扫码后自动打开配对链接。</p><p>2. 登录并确认要连接的 PiDock。</p><p>3. 回到本机确认设备名称与权限。</p></div><div class="inline-notice">二维码在本机生成，只包含短时单次凭据，不包含长期令牌、项目名称或本机路径。</div>`,`${button('刷新二维码','refresh-pair')}${button('模拟完成配对','complete-pair','primary')}`);requestAnimationFrame(drawPairingQr)}
function remotePreview(){const r=state.remote;modal('手机视图预览',`<div class="phone-preview"><div class="phone-status"><span>9:41</span><span>${r.connected?'已连接':'离线'}</span></div><header><span class="brandmark">π</span><div><strong>PiDock</strong><small>${esc(r.workspaceName)}</small></div></header><main><div class="mobile-section-title">项目</div><button class="mobile-project"><span><strong>Adber</strong><small>2 个任务 · 4 个服务运行中</small></span>${icon('right')}</button><div class="mobile-section-title">最近任务</div><button class="mobile-task"><span class="dot live"></span><span><strong>对账单详情 · 本地联调</strong><small>Agent 空闲 · 刚刚更新</small></span></button><button class="mobile-task"><span class="dot"></span><span><strong>运单地址校验</strong><small>服务已停止 · 12 分钟前</small></span></button><div class="mobile-chat"><strong>实现与验证</strong><p>当前任务已准备独立的工作副本…</p><div class="mobile-compose">发送消息… ${icon('arrow')}</div></div></main><nav><span>项目</span><span>任务</span><span>对话</span><span>设置</span></nav></div><p class="phone-caption">移动端优先覆盖查看状态、进入对话和少量管理；文件编辑、终端和浏览器控制不作为默认入口。</p>`)}

function capabilityAction(a,arg){
  if(a==='capability-type'){state.capabilityType=arg;render()}
  else if(a==='capability-detail'){const [type,index]=arg.split(':');capabilityDetail(type,+index)}
  else if(a==='add-capability')addCapabilityDialog(arg);
  else if(a==='save-capability'){const name=document.querySelector('#capability-name').value.trim(),source=document.querySelector('#capability-source').value.trim();if(!name||!source){toast('请填写名称和来源');return true}state.capabilities[arg].push({name,description:'新添加的能力，等待审阅',source,scope:document.querySelector('#capability-scope').value,enabled:false,status:'待审阅',risk:'尚未声明'});closeModal();render();toast('已添加为停用，不会加载或连接')}
  else if(a==='toggle-capability'){const [type,index]=arg.split(':');const item=state.capabilities[type]?.[+index];if(!item)return true;item.enabled=!item.enabled;item.status=item.enabled?(type==='mcp'?'已连接':type==='extension'?'已加载':type==='package'?'已安装':'可用'):'已停用';closeModal();render();toast(`${item.name} 已模拟${item.enabled?'启用':'停用'}`)}
  else if(a==='remote-mode'){state.remote.mode=arg;state.remote.connected=false;render()}
  else if(a==='toggle-remote'){const url=document.querySelector('#remote-url')?.value.trim(),name=document.querySelector('#remote-workspace-name')?.value.trim()||state.remote.workspaceName;if(url&&!/^https:\/\//.test(url)){toast('远程入口需要使用 HTTPS');return true}if(url){if(state.remote.mode==='gateway')state.remote.gatewayUrl=url;else state.remote.funnelUrl=url}state.remote.workspaceName=name;state.remote.connected=!state.remote.connected;render();toast(state.remote.connected?'已模拟启用远程入口':'已模拟断开远程入口')}
  else if(a==='remote-detect')toast('原型未调用本机 Tailscale；当前机器的启动脚本不可用');
  else if(a==='remote-preview')remotePreview();else if(a==='pair-device')pairDeviceDialog();else if(a==='refresh-pair'){state.remote.pairVersion++;pairDeviceDialog();toast('旧二维码已失效') }else if(a==='complete-pair'){state.remote.devices.unshift({name:'新的移动设备',detail:'等待本机确认 · 刚刚',current:false});closeModal();render();toast('已加入模拟设备，可单独撤销')}
  else if(a==='revoke-device'){state.remote.devices.splice(+arg,1);render();toast('已撤销模拟设备')}
  else return false;
  return true;
}

document.addEventListener('click',event=>{
  const target=event.target.closest('[data-action]');if(!target)return;
  const [action,...rest]=target.dataset.action.split(':');
  if(capabilityAction(action,rest.join(':'))){event.preventDefault();event.stopImmediatePropagation()}
});
document.addEventListener('change',event=>{
  if(event.target.dataset.capabilityToggle){const [type,index]=event.target.dataset.capabilityToggle.split(':');const item=state.capabilities[type][+index];item.enabled=event.target.checked;item.status=item.enabled?(type==='mcp'?'已连接':type==='extension'?'已加载':type==='package'?'已安装':'可用'):'已停用';render();toast(`${item.name} 已模拟${item.enabled?'启用':'停用'}`)}
  if(event.target.dataset.remotePermission){state.remote.permissions[event.target.dataset.remotePermission]=event.target.checked;render();toast('已更新模拟移动端权限')}
});
