/* THROWAWAY — projects can combine Git repositories and ordinary directories. */
function projectDirectories(p=currentProject()){return p?.directories||[]}
function directoryProject(){return projectDirectories().length>0}
function directoryTask(){return !!task()&&!task().repos.length}
function taskDirectories(){return task()?.directories||[]}
function directoryLinkName(d){return d.linkName||'dir-'+d.id.replace(/[^a-zA-Z0-9]/g,'').slice(0,8).toLowerCase()}
function directoryLinkPath(d,t=task()){return workspacePath(t.workspaceRoot,t.workspaceKey,directoryLinkName(d))}
function snapshotTaskDirectories(directories){return directories.map(d=>({...structuredClone(d),linkName:directoryLinkName(d)}))}
function workspaceEntrySummary(){return `<div class="workspace-preview"><strong>pi 工作目录</strong><code>${esc(workspacePath(task().workspaceRoot,task().workspaceKey))}</code><small>${task().repos.map(i=>esc(repos[i])+'/ · worktree').concat(taskDirectories().map(d=>esc(directoryLinkName(d))+'/ → '+esc(d.name))).join('<br>')}</small></div>`}
function updateTaskEntryPreview(){const preview=document.querySelector('#task-entry-preview');if(!preview)return;const root=document.querySelector('#task-root')?.value.trim()??task().workspaceRoot;const git=[...document.querySelectorAll('input[name=repo]:checked')].map(el=>`<div class="task-entry"><strong>${esc(repos[+el.value])}</strong><small>worktree</small><code>${esc(workspacePath(root,pendingWorkspaceKey,repos[+el.value]))}</code></div>`);const dirs=[...document.querySelectorAll('input[name=task-directory]:checked')].map(el=>{const d=taskDirectories().find(d=>d.id===el.value)||projectDirectories().find(d=>d.id===el.value);return `<div class="task-entry"><strong>${esc(d.name)}</strong><small>软链接 · 修改影响原目录</small><code>${esc(workspacePath(root,pendingWorkspaceKey,directoryLinkName(d)))}</code><small>→ ${esc(d.path)}</small></div>`});preview.innerHTML=git.concat(dirs).join('')||'<small>请选择本次需要的仓库或普通目录。</small>'}
function selectedDirectory(){return taskDirectories().find(d=>d.id===task()?.activeDirectoryId)||(directoryTask()?taskDirectories()[0]:null)}
function directoryRow(d={},locked=false){return `<div class="project-directory-row" data-directory-id="${d.id||crypto.randomUUID()}"><input class="directory-name" aria-label="目录名称" value="${esc(d.name||'')}" placeholder="例如：设计资料" ${locked?'readonly':''}><input class="directory-path" aria-label="目录路径" value="${esc(d.path||'')}" placeholder="/Users/name/Documents/design" ${locked?'readonly':''}><span class="badge">普通目录</span><button class="iconbtn" data-action="remove-project-directory" ${locked?'disabled':''} aria-label="移除此目录" title="${locked?'任务使用中':'移除目录登记'}">${icon('close')}</button></div>`}
function projectLocationFields(p){return `<div class="between toolbar-space"><h3>普通目录</h3>${button('添加目录','add-project-directory','sm','plus')}</div><p class="note">可与 Git 仓库同时加入项目，任务中按需选择。路径仅作原型展示。</p><div id="project-directory-list">${projectDirectories(p).map(d=>directoryRow(d,state.tasks.some(t=>t.projectId===p.id&&t.directories?.some(x=>x.id===d.id)))).join('')}</div>`}
function readProjectDirectories(){const rows=[...document.querySelectorAll('.project-directory-row')].map(row=>({id:row.dataset.directoryId,name:row.querySelector('.directory-name').value.trim(),path:row.querySelector('.directory-path').value.trim()}));if(rows.some(d=>!d.name||!validWorkspaceRoot(d.path))){toast('请填写每个普通目录的名称和完整路径');return null}if(new Set(rows.map(d=>d.path.replace(/[\\/]+$/,''))).size!==rows.length){toast('请勿重复添加同一路径');return null}return rows}
function directoryProjectPage(){const p=currentProject();return `<div class="page"><div class="between"><div><div class="view-label">PROJECT</div><h1>${esc(p.name)}</h1></div><div class="flex">${button('项目管理','projects')}${button('新建任务','newtask','primary','plus')}</div></div><p class="page-intro">${esc(p.description||'在项目中组织代码、资料和任务。')}</p><div class="between"><h2>项目目录</h2>${button('管理目录','edit-project:'+p.id,'sm','folder')}</div><div class="management-list toolbar-space">${p.repos.map(i=>`<div class="management-row"><div><strong>${repos[i]}</strong><small>已注册仓库 · 创建任务时准备独立工作副本</small></div><span class="badge">Git 仓库</span></div>`).join('')}${projectDirectories().map(d=>`<div class="management-row"><div><strong>${esc(d.name)}</strong><small>${esc(d.path)}</small></div><span class="badge">普通目录 · 软链接接入</span></div>`).join('')}</div><p class="note">Git 仓库创建独立 worktree；普通目录通过软链接加入任务目录，修改会影响原目录。</p><h2 class="toolbar-space">继续工作</h2><div class="grid2 toolbar-space">${projectTasks().filter(t=>!t.archived).map(t=>`<div class="card taskcard" data-action="task:${state.tasks.indexOf(t)}" role="button" tabindex="0"><h3>${esc(t.name)}</h3><small>${t.repos.length} 个 Git 仓库 · ${t.directories?.length||0} 个普通目录</small></div>`).join('')||'<div class="empty">创建任务时选择本次需要的仓库和目录。</div>'}</div></div>`}
function taskDirectoryChoices(add){return projectDirectories().length?`<h3 class="toolbar-space">普通目录 · 通过软链接加入</h3>${projectDirectories().map(d=>{const exists=add&&taskDirectories().some(x=>x.id===d.id);return `<label class="check-row"><input type="checkbox" name="task-directory" value="${d.id}" ${exists?'checked disabled':!add?'checked':''}><span><strong>${esc(d.name)}</strong><br><small>${esc(d.path)}${exists?' · 已加入':''}</small></span></label>`}).join('')}<p class="note">任务中自动生成英文数字链接名，中文名称只用于显示。修改链接内文件会影响原目录；多个任务引用时共享文件。</p>`:''}
function refreshTaskDirectoryForm(){for(const input of document.querySelectorAll('.branch[data-repo]')){const selected=document.querySelector('input[name=repo][value="'+input.dataset.repo+'"]');input.disabled=!selected.checked||selected.disabled}const hasGit=!!document.querySelector('input[name=repo]:checked:not(:disabled)');for(const el of document.querySelectorAll('.git-task-fields,.baseline-policy,.task-preview-scenario'))el.hidden=!hasGit;const submit=document.querySelector('[data-action="confirm-newtask"],[data-action="confirm-addrepo"]');if(submit)submit.textContent=hasGit?'获取最新基线并继续':submit.dataset.action==='confirm-addrepo'?'添加目录':'创建任务';updateWorkspacePreview()}
document.addEventListener('change',e=>{if(['repo','task-directory'].includes(e.target.name))refreshTaskDirectoryForm()});
function directoryHeader(){return `<header class="taskheader"><div class="between"><div><div class="view-label">TASK · 普通目录</div><h1>${esc(task().name)}</h1></div><div class="actionset">${button('添加目录','addrepo','','plus')}${button('文件','tab:files','','folder')}${button('终端','tab:terminal','','terminal')}${subagentButton()}<button class="iconbtn" data-action="taskmenu" aria-label="任务操作">${icon('more')}</button></div></div><div class="flex meta"><span>${taskDirectories().length} 个普通目录 · 通过软链接加入</span></div></header>`}
function directoryRootChoices(){return workspaceEntrySummary()+`<div class="directory-root-choices">${task().repos.map(i=>button(repos[i],'repo:'+i,'sm '+(!selectedDirectory()&&state.fileRepo===i?'primary':''),'branch')).join('')}${taskDirectories().map(d=>button(esc(d.name),'select-directory:'+d.id,'sm '+(selectedDirectory()?.id===d.id?'primary':''),'folder')).join('')}</div>`}
function directoryPanel(){const d=selectedDirectory();if(!d)return '<div class="empty">请选择任务目录。</div>';const location=`<div class="workspace-preview"><strong>任务内软链接</strong><code>${esc(directoryLinkPath(d))}</code><small>指向原目录：${esc(d.path)}<br>修改会影响原目录 · 文件未隔离</small></div>`;if(state.tab==='terminal')return `${directoryRootChoices()}<div class="panel-heading"><strong>终端 · ${esc(d.name)}</strong></div>${location}<div class="terminal"><span class="muted">原型终端：拟从以上链接位置打开，仅回显，不执行命令。</span><div id="terminal-output"></div>$ <input id="terminal-input" aria-label="模拟终端命令" placeholder="输入示例命令"></div>`;return `${directoryRootChoices()}<div class="panel-heading"><strong>${esc(d.name)}</strong><span class="badge">软链接</span></div>${location}<div class="filetree">▾ ${esc(directoryLinkName(d))} → ${esc(d.name)}<br>　 README.md（示例）</div><div class="codeblock"># 项目资料\n\n在这里整理说明与待办。</div>${button('引用示例文件','quote-directory-file','sm','chat')}<p class="note">未读取真实目录。此目录不提供 Git 差异、分支或提交操作。</p>`}
function directoryWorkspace(){return `<div class="taskbody ${task().openTools?.length?'':'tools-closed'}">${conversation()}${workbench()}</div>`}
function directoryAction(action,arg){
 if(action==='add-project-directory'){document.querySelector('#project-directory-list').insertAdjacentHTML('beforeend',directoryRow());return true}
 if(action==='remove-project-directory')return false;
 if(action==='select-directory'){task().activeDirectoryId=arg;openTool(task().activeTool==='terminal'?'terminal':'files');render();return true}
 if(action==='repo'){if(task()){task().activeDirectoryId=null;if(task().activeTool==='terminal'){state.fileRepo=+arg;render();return true}}return false}
 if(action==='quote-directory-file'){const d=selectedDirectory();task().refs.push({type:'file',name:directoryLinkName(d)+'/README.md',source:directoryLinkPath(d)+' → '+d.path+' · 示例引用，尚未读取'});render();return true}
 if(action==='cleanup'){const target=state.tasks[+arg];if(!target?.directories?.length)return false;modal('清理任务资源',`<p class="page-intro">普通目录只移除任务内的软链接，保留原目录及其中全部文件。Git 工作副本需单独审阅变更后清理。</p>${target.directories.map(d=>`<div class="workspace-preview"><strong>移除软链接</strong><code>${esc(directoryLinkPath(d,target))}</code><small>保留原目录：${esc(d.path)}</small></div>`).join('')}<p class="preview-note">当前原型不执行删除。</p>`);return true}
 return false;
}
document.addEventListener('click',e=>{const button=e.target.closest('[data-action="remove-project-directory"]');if(button&&!button.disabled)button.closest('.project-directory-row').remove()});
