/* THROWAWAY — management UI, page-memory state only. */
function initializeManagement(){
  state.projectId='adber';
  state.projects=[{id:'adber',name:'Adber',description:'微服务开发工作台',repos:[0,1,2,3],environments:[
    {id:'development',name:'开发环境',description:'日常开发与远程开发依赖',version:12,services:structuredClone(serviceSeed.slice(0,4)),rows:structuredClone(seedEnvRows)},
    {id:'testing',name:'测试环境',description:'本地联调使用的远程测试依赖',version:12,services:structuredClone(serviceSeed.slice(0,4)),rows:structuredClone(seedEnvRows)}]}];
  state.envId='testing';
}
function currentProject(){return state.projects.find(p=>p.id===state.projectId)}
function projectTasks(){return state.tasks.filter(t=>t.projectId===state.projectId)}
function currentEnvironment(){return currentProject()?.environments.find(e=>e.id===state.envId)}
function environmentRows(){return currentEnvironment()?.rows||[]}
function selectProject(id){
  state.projectId=id;state.task=state.tasks.findIndex(t=>t.projectId===id&&!t.archived);
  const env=currentProject()?.environments[0];state.envId=env?.id;state.env=env?.name||'';state.envDirty=false;state.envScope=task()?'task':'shared';state.view='project';closeModal();render();
}
function projectsDialog(){modal('项目管理',`<p class="page-intro">切换项目，或管理项目的目录、仓库与名称。</p><div class="management-list">${state.projects.map(p=>`<div class="management-row"><div><strong>${esc(p.name)}</strong><small>${esc(p.description||'未填写说明')} · ${state.tasks.filter(t=>t.projectId===p.id).length} 个任务</small></div><div class="flex">${button(p.id===state.projectId?'当前项目':'切换','switch-project:'+p.id,'sm')}${button('编辑','edit-project:'+p.id,'sm')}${button('删除','delete-project:'+p.id,'sm danger')}</div></div>`).join('')||'<div class="empty">还没有项目</div>'}</div>`,button('新建项目','new-project','primary','plus'))}
function projectDialog(id){const p=state.projects.find(p=>p.id===id);modal(p?'编辑项目':'新建项目',`<div class="formfield"><label for="project-name">项目名称</label><input id="project-name" value="${esc(p?.name||'')}" placeholder="例如：订单系统"></div><div class="formfield"><label for="project-description">说明</label><input id="project-description" value="${esc(p?.description||'')}"></div><div id="project-repositories"><h3>关联已注册仓库</h3><small>以下为原型示例仓库，可暂不选择，稍后再绑定。</small>${repos.map((r,i)=>{const used=p&&state.tasks.some(t=>t.projectId===p.id&&t.repos.includes(i));return `<label class="check-row"><input type="checkbox" name="project-repo" value="${i}" ${p?.repos.includes(i)?'checked':''} ${used?'disabled':''}><span>${r}</span>${used?'<small>任务使用中</small>':''}</label>`}).join('')}</div>${projectLocationFields(p)}`,button(p?'保存项目':'创建项目','save-project:'+(id||'new'),'primary'))}
function saveProject(id){
  const name=document.querySelector('#project-name').value.trim();if(!name){toast('请填写项目名称');return}
  if(state.projects.some(p=>p.id!==id&&p.name===name)){toast('已有同名项目，请使用其他名称');return}
  const directories=readProjectDirectories();if(!directories)return;
  const values={directories,name,description:document.querySelector('#project-description').value.trim(),repos:[...document.querySelectorAll('input[name=project-repo]:checked')].map(e=>+e.value)};
  if(id==='new'){const p={id:crypto.randomUUID(),...values,environments:[]};state.projects.push(p);selectProject(p.id)}else{Object.assign(state.projects.find(p=>p.id===id),values);closeModal();render()}
  toast('项目已保存到原型内存');
}
function deleteProjectDialog(id){const p=state.projects.find(p=>p.id===id);if(!p)return;const tasks=state.tasks.filter(t=>t.projectId===id);modal('删除项目',`<h3>${esc(p.name)}</h3>${tasks.length?`<div class="inline-notice">还有 ${tasks.length} 个关联任务（包含已归档任务），暂不能删除项目。</div><p class="page-intro">请先在任务清理流程中处理这些任务；归档不会解除关联。</p>${tasks.map(t=>`<div class="check-row">${esc(t.name)} <small>${t.archived?'已归档':'进行中'}</small></div>`).join('')}`:`<p class="page-intro">将移除该项目的登记、仓库绑定和 ${p.environments.length} 个环境配置。原始仓库和磁盘上的共享模板文件保留。</p><div class="preview-note">此操作仅演示删除范围，原型中刷新页面可重置。</div>`}`,tasks.length?'':button('删除项目','confirm-delete-project:'+id,'danger'))}
function managementProjectPage(){if(directoryProject())return directoryProjectPage();const p=currentProject();if(!p)return `<div class="page"><h1>项目</h1><div class="empty"><h3>创建第一个项目</h3><p>项目用于组织仓库、任务与运行环境。</p>${button('新建项目','new-project','primary','plus')}</div></div>`;
 return `<div class="page"><div class="between"><div><div class="view-label">PROJECT</div><h1>${esc(p.name)}</h1></div><div class="flex">${button('项目管理','projects')}${button('新建任务','newtask','primary','plus')}</div></div><p class="page-intro">${esc(p.description||'在项目中组织仓库、任务与运行环境。')}</p><div class="grid3"><div class="card"><small>进行中的任务</small><div class="stat">${projectTasks().filter(t=>!t.archived).length}</div></div><div class="card"><small>已绑定仓库</small><div class="stat">${p.repos.length}</div></div><div class="card"><small>运行环境</small><div class="stat">${p.environments.length}</div>${button('管理环境','view:env','sm')}</div></div><h2 class="toolbar-space">继续工作</h2><div class="grid2 toolbar-space">${projectTasks().filter(t=>!t.archived).map(t=>`<div class="card taskcard" data-action="task:${state.tasks.indexOf(t)}" role="button" tabindex="0"><h3>${esc(t.name)}</h3><p class="page-intro">${t.repos.map(i=>repos[i]).join(' · ')}</p><span class="badge">${esc(t.env)}</span></div>`).join('')||'<div class="empty">还没有任务，先绑定仓库并创建环境。</div>'}</div><div class="between toolbar-space rowgap"><h2>项目仓库</h2>${button('管理仓库','edit-project:'+p.id,'sm','folder')}</div>${p.repos.map(i=>`<div class="check-row">${icon('folder')}<strong>${repos[i]}</strong><small>本机已注册（示例）</small></div>`).join('')||'<p class="page-intro">尚未绑定仓库。</p>'}</div>`;
}
function environmentsDialog(){const p=currentProject();if(!p){projectsDialog();return}modal('环境管理',`<p class="page-intro">${esc(p.name)} · 环境的名称和说明在这里管理，变量与启动方式在环境页面编辑。</p><div class="management-list">${p.environments.map(e=>`<div class="management-row"><div><strong>${esc(e.name)}</strong><small>${esc(e.description||'未填写说明')} · v${e.version}</small></div><div class="flex">${button('编辑','edit-environment:'+e.id,'sm')}${button('删除','delete-environment:'+e.id,'sm danger')}</div></div>`).join('')||'<div class="empty">还没有环境</div>'}</div>`,button('新增环境','new-environment','primary','plus'))}
function environmentDialog(id){const e=currentProject()?.environments.find(e=>e.id===id);modal(e?'编辑环境':'新增环境',`<div class="formfield"><label for="environment-name">环境名称</label><input id="environment-name" value="${esc(e?.name||'')}" placeholder="例如：集成测试"></div><div class="formfield"><label for="environment-description">说明</label><input id="environment-description" value="${esc(e?.description||'')}" placeholder="说明远程依赖和使用场景"></div><div class="preview-note">${e?'修改名称和说明不改变任务采用的模板版本，也不重启服务。':'创建空环境后，前往共享模板添加变量与服务配置。'}</div>`,button(e?'保存环境':'创建环境','save-environment:'+(id||'new'),'primary'))}
function saveEnvironment(id){const p=currentProject();if(!p)return;const name=document.querySelector('#environment-name').value.trim();if(!name){toast('请填写环境名称');return}if(p.environments.some(e=>e.id!==id&&e.name===name)){toast('当前项目已有同名环境');return}const description=document.querySelector('#environment-description').value.trim();let e=p.environments.find(e=>e.id===id);if(e){Object.assign(e,{name,description});for(const t of projectTasks())if(t.envId===id)t.env=name}else{e={id:crypto.randomUUID(),name,description,version:1,services:[],rows:[]};p.environments.push(e)}state.envId=e.id;state.env=e.name;state.envScope='shared';state.envDirty=false;state.view='env';closeModal();render();toast('环境已保存；任务的模板版本与运行状态保留')}
function deleteEnvironmentDialog(id){const e=currentProject()?.environments.find(e=>e.id===id);if(!e)return;const tasks=projectTasks().filter(t=>t.envId===id);modal('删除环境',`<h3>${esc(e.name)}</h3>${tasks.length?`<div class="inline-notice">${tasks.length} 个任务正在引用此环境（包含已归档任务），暂不能删除。</div>${tasks.map(t=>`<div class="check-row">${esc(t.name)} <small>${t.version}</small></div>`).join('')}`:'<p class="page-intro">将移除此环境及其配置。其他环境和远程服务不受影响。</p>'}`,tasks.length?'':button('删除环境','confirm-delete-environment:'+id,'danger'))}
function managedEnvironmentPage(){const p=currentProject();if(!p)return managementProjectPage();if(!currentEnvironment())return `<div class="page"><div class="between"><h1>环境与服务</h1>${button('新增环境','new-environment','primary','plus')}</div><div class="empty">${esc(p.name)} 还没有环境。先创建环境，再配置变量与服务。</div></div>`;if(state.envScope==='task'&&(!task()||task().envId!==state.envId))state.envScope='shared';return environmentEditor()}
function sessionManagementDialog(){const t=task();if(!t)return;modal('会话管理',`<p class="page-intro">归档收起会话，历史、草稿、模型选择和用量保留。任务代码与服务继续保留。</p><div class="management-list">${t.sessions.map((name,i)=>`<div class="management-row"><div><strong>${esc(name)}</strong><small>${t.archivedSessions.includes(i)?'已归档':i===t.session?'当前会话':'可切换'}</small></div><div class="flex">${t.archivedSessions.includes(i)?button('恢复','restore-session:'+i,'sm'):button('归档','archive-session:'+i,'sm','archive')}</div></div>`).join('')}</div>`)}
function archiveSession(i){const t=task();if(!t||t.archivedSessions.includes(i))return;if(t.busySession===i){toast('请先停止会话执行，再归档');return}t.archivedSessions.push(i);if(t.session===i){const next=t.sessions.findIndex((_,n)=>!t.archivedSessions.includes(n));if(next>=0)t.session=next;else{t.sessions.push('新会话 '+t.sessions.length);t.session=t.sessions.length-1}}render();sessionManagementDialog();toast('会话已归档，历史与草稿保留')}
function manageAction(a,arg){
 if(a==='add-env-row'){const d=environmentDraft();d.rows.push({id:crypto.randomUUID(),key:'',value:''});d.dirty=true;render();document.querySelector('.env-table tbody tr:last-child .env-key-input')?.focus()}else if(a==='remove-env-row'){const d=environmentDraft();d.rows=d.rows.filter(r=>r.id!==arg);d.dirty=true;d.error='';render()}else if(a==='save-env')saveEnvironmentRows();else if(a==='commit-env-rows')commitEnvironmentRows();else if(a==='projects')projectsDialog();else if(a==='new-project')projectDialog();else if(a==='edit-project')projectDialog(arg);else if(a==='save-project')saveProject(arg);else if(a==='switch-project')selectProject(arg);else if(a==='delete-project')deleteProjectDialog(arg);
 else if(a==='confirm-delete-project'){if(state.tasks.some(t=>t.projectId===arg)){deleteProjectDialog(arg);return true}state.projects=state.projects.filter(p=>p.id!==arg);if(state.projectId===arg)selectProject(state.projects[0]?.id);else{closeModal();render()}toast('已移除模拟项目登记，未删除磁盘文件')}
 else if(a==='environments')environmentsDialog();else if(a==='new-environment')environmentDialog();else if(a==='edit-environment')environmentDialog(arg);else if(a==='save-environment')saveEnvironment(arg);else if(a==='delete-environment')deleteEnvironmentDialog(arg);
 else if(a==='confirm-delete-environment'){if(projectTasks().some(t=>t.envId===arg)){deleteEnvironmentDialog(arg);return true}const p=currentProject();p.environments=p.environments.filter(e=>e.id!==arg);if(state.envId===arg){state.envId=p.environments[0]?.id;state.env=p.environments[0]?.name||''}closeModal();render();toast('已删除模拟环境')}
 else if(a==='manage-sessions')sessionManagementDialog();else if(a==='archive-session')archiveSession(+arg);else if(a==='restore-session'){task().archivedSessions=task().archivedSessions.filter(i=>i!==+arg);task().session=+arg;closeModal();render();toast('会话已恢复')}
 else return false;return true;
}

const environmentDrafts=new Map();
function environmentDraft(){
 const key=[state.projectId,state.envId,state.envScope,state.envScope==='task'?task()?.workspaceKey:''].join(':');
 if(!environmentDrafts.has(key)){
  const scope=state.envScope, values=state.envValues[scope];
  const seed=scope==='private'?environmentRows().filter(r=>r[0]==='DATABASE_PASSWORD'):environmentRows();
  const auto=scope==='task'&&task()?.services.length>=4&&!directoryTask()?{PORT:String(task().services[1].port),INVOICE_SERVICE_ENDPOINT:'127.0.0.1:'+task().services[2].port,SHIPMENT_SERVICE_V1_ENDPOINT:'127.0.0.1:'+task().services[3].port}:{};
  const rows=seed.map(([name,value])=>({id:crypto.randomUUID(),key:name,value:values[name]??auto[name]??(scope==='private'?'':value)}));
  environmentDrafts.set(key,{rows,original:structuredClone(rows),dirty:false,error:''});
 }
 return environmentDrafts.get(key);
}
function sensitiveEnvKey(key){return /PASSWORD|SECRET|TOKEN|API_KEY/i.test(key)}
function environmentTable(){const d=environmentDraft();state.envDirty=d.dirty;return `<div class="table-wrap env-table-wrap"><table class="env-table"><thead><tr><th>KEY</th><th>VALUE</th></tr></thead><tbody>${d.rows.map((r,i)=>`<tr><td><input class="env-key-input" aria-label="第 ${i+1} 行 KEY" data-env-row="${r.id}" data-env-field="key" value="${esc(r.key)}" placeholder="例如 API_ENDPOINT" spellcheck="false"></td><td><div class="env-value-cell"><input aria-label="第 ${i+1} 行 VALUE" data-env-row="${r.id}" data-env-field="value" value="${esc(r.value)}" placeholder="变量值，可为空" ${sensitiveEnvKey(r.key)?'type="password" autocomplete="off"':''} spellcheck="false"><button class="iconbtn" data-action="remove-env-row:${r.id}" aria-label="删除第 ${i+1} 行" title="删除此行">${icon('close')}</button></div></td></tr>`).join('')||'<tr><td colspan="2" class="env-empty">尚未添加变量，点击下方「新增一行」。</td></tr>'}</tbody></table><button class="env-add-row" data-action="add-env-row">${icon('plus')} 新增一行</button></div><p id="env-list-error" class="env-list-error" role="alert">${esc(d.error)}</p>`}
function updateEnvironmentRow(input){const d=environmentDraft();const r=d.rows.find(row=>row.id===input.dataset.envRow);if(!r)return;r[input.dataset.envField]=input.value;d.dirty=true;d.error='';state.envDirty=true;const error=document.querySelector('#env-list-error');if(error)error.textContent='';const save=document.querySelector('[data-action="save-env"]');if(save)save.textContent='保存更改 · 未保存';}
function validateEnvironmentRows(){const d=environmentDraft();const seen=new Set();for(let i=0;i<d.rows.length;i++){const r=d.rows[i],key=r.key.trim();let error='';if(!key)error=`第 ${i+1} 行 KEY 不能为空，请填写或删除此行。`;else if(!/^[A-Za-z_][A-Za-z0-9_]*$/.test(key))error=`第 ${i+1} 行 KEY 只能包含字母、数字和下划线，且不能以数字开头。`;else if(seen.has(key))error=`第 ${i+1} 行 KEY「${key}」重复，请使用不同名称。`;if(error){d.error=error;document.querySelector('#env-list-error').textContent=error;document.querySelector(`[data-env-row="${r.id}"][data-env-field="key"]`).focus();return false}seen.add(key)}return true}
function saveEnvironmentRows(){const d=environmentDraft();if(!validateEnvironmentRows())return;if(!d.dirty){toast('没有待保存的更改');return}if(state.envScope==='shared'){
 const before=Object.fromEntries(d.original.map(r=>[r.key.trim(),r.value]));const after=Object.fromEntries(d.rows.map(r=>[r.key.trim(),r.value]));const keys=new Set([...Object.keys(before),...Object.keys(after)]);
 const diff=[...keys].filter(k=>before[k]!==after[k]||Object.hasOwn(before,k)!==Object.hasOwn(after,k)).map(k=>{const show=(obj)=>Object.hasOwn(obj,k)?(sensitiveEnvKey(k)?'[敏感值引用]':obj[k]||'（空值）'):'（无）';return `<div><strong>${esc(k)}</strong><br>${esc(show(before))} → ${esc(show(after))}</div>`}).join('');
 modal('审阅共享模板变更',`<p class="page-intro">${esc(currentEnvironment().name)}：v${currentEnvironment().version} → v${currentEnvironment().version+1}。已有任务保留采用的版本。</p><div class="approval-diff">${diff||'字段格式调整'}</div>`,button('确认保存新版本','commit-env-rows','primary'));
 }else commitEnvironmentRows();
}
function commitEnvironmentRows(){const d=environmentDraft();const rows=d.rows.map(r=>({...r,key:r.key.trim()}));const values=state.envValues[state.envScope];for(const key of Object.keys(values))delete values[key];Object.assign(values,Object.fromEntries(rows.map(r=>[r.key,r.value])));if(state.envScope==='shared'){currentEnvironment().rows=rows.map(r=>[r.key,r.value,'共享环境模板']);currentEnvironment().version++}d.rows=rows;d.original=structuredClone(rows);d.dirty=false;d.error='';state.envDirty=false;closeModal();render();toast('列表已模拟保存；已有任务与运行服务保留')}
