/* THROWAWAY - scheduled Agent session UI exploration. All state stays in page memory. */
function initializeSchedules(){
  state.scheduleFilter='all';
  state.schedules=[
    {id:'weekly-changes',name:'每周仓库改动摘要',projectId:'adber',provider:0,model:'Claude Sonnet',prompt:'统计本周各 Git 仓库相对上周日基线的合并记录、主要改动和风险，生成面向研发团队的摘要，并通过已配置的研发通知渠道发送给所有研发。',kind:'weekly',time:'18:00',weekday:'0',cron:'',timezone:'Asia/Shanghai',permission:'default',enabled:true,next:'周日 18:00',last:'上周日 18:04 · 待确认'},
    {id:'daily-standup',name:'站会主题内容',projectId:'adber',provider:1,model:'GPT',prompt:'根据昨天以来的任务和 Git 变更，生成今天站会的主题、进展、阻塞和需要协调的事项，并将结果保留在本次会话中。',kind:'cron',time:'',weekday:'1',cron:'15 9 * * 1-5',timezone:'Asia/Shanghai',permission:'read',enabled:true,next:'明天 09:15',last:'今天 09:16 · 成功'},
    {id:'weekly-contribution',name:'每周代码贡献度',projectId:'adber',provider:0,model:'Claude Sonnet',prompt:'按作者统计本周各 Git 仓库的提交、评审与改动范围，说明统计口径并避免将代码行数直接等同于绩效；将完整统计保留在会话中。',kind:'weekly',time:'19:00',weekday:'0',cron:'',timezone:'Asia/Shanghai',permission:'read',enabled:false,next:'已暂停',last:'尚未执行'}
  ];
  state.scheduleRuns=[
    {id:'run-1',scheduleId:'daily-standup',started:'今天 09:15',status:'成功',detail:'主题内容已生成',taskIndex:null,sessionIndex:0},
    {id:'run-2',scheduleId:'weekly-changes',started:'上周日 18:00',status:'待确认',detail:'群发前等待确认',taskIndex:null,sessionIndex:0},
    {id:'run-3',scheduleId:'weekly-changes',started:'09/13 18:00',status:'失败',detail:'摘要已生成 · 通知工具失败',taskIndex:null,sessionIndex:1}
  ];
  const sessionsBySchedule={
    'weekly-changes':['09/20 18:00 · 改动摘要','09/13 18:00 · 改动摘要'],
    'daily-standup':['今天 09:15 · 站会主题','昨天 09:15 · 站会主题'],
    'weekly-contribution':['等待首次执行']
  };
  for(const s of state.schedules){
    const project=scheduleProject(s.projectId),labels=sessionsBySchedule[s.id];
    const t=prepareSessions(makeTask(s.name,'schedule-'+s.id,false,project?.repos||[]));
    Object.assign(t,{taskType:'scheduled',scheduleId:s.id,projectId:s.projectId,isNew:true,sessions:labels,session:0,archivedSessions:[],messages:[],permissionsBySession:{}});
    t.sessionData=Object.fromEntries(labels.map((_,i)=>[i,{draft:'',refs:[],provider:s.provider,model:s.model,context:i===0?4.2:2.8,tokens:i===0?12.6:8.4}]));
    labels.forEach((label,i)=>{if(label==='等待首次执行')return;t.permissionsBySession[i]=s.permission;t.messages.push({role:'user',text:s.prompt,permission:s.permission,session:i},{role:'agent',text:s.id==='weekly-changes'?(i===0?'摘要已生成，发送前等待本次确认。':'摘要已生成，通知步骤失败，请核对送达情况后处理。'):'本次执行完成，结果保留在会话中。',session:i})});
    state.tasks.push(t);s.taskIndex=state.tasks.length-1;
  }
  for(const run of state.scheduleRuns)run.taskIndex=state.schedules.find(s=>s.id===run.scheduleId)?.taskIndex??null;
}

const scheduleKinds={once:'仅一次',daily:'每天',weekly:'每周',cron:'自定义周期'};
const scheduleTemplates=[
  {id:'weekly-summary',name:'每周仓库改动摘要',label:'周日 18:00',kind:'weekly',weekday:'0',time:'18:00',prompt:'汇总当前项目各 Git 仓库截至本次执行时间过去 7 天的改动。按功能、修复、重构和风险整理，附提交或合并请求依据，生成面向全体研发的周报。先将完整结果保留在本次会话；如需群发，请在此补充渠道与接收人，并遵循可用工具和会话权限。'},
  {id:'standup',name:'站会主题准备',label:'工作日 09:15',kind:'cron',cron:'15 9 * * 1-5',prompt:'为今天的研发站会准备主题。检查当前项目自上一个工作日同一计划时刻至本次执行时间的 Git 变更，以及可访问的任务记录，整理进展、明确记录的阻塞、待协调事项和建议讨论顺序。周一覆盖周末；工作日按周一至周五解释。不要仅凭提交记录推断任务已完成或成员受阻。将结果保留在本次会话。'},
  {id:'contribution',name:'每周代码贡献统计',label:'周日 19:00',kind:'weekly',weekday:'0',time:'19:00',prompt:'统计当前项目各 Git 仓库截至本次执行时间过去 7 天的代码贡献。按作者列出提交、主要改动范围和可获取的评审记录，说明分支范围、作者合并、合并提交与机器人过滤口径，附依据。代码行数仅作参考，不等同绩效，不生成简单绩效排名。将完整统计保留在本次会话。'},
  {id:'risk-review',name:'每日代码风险巡检',label:'工作日 17:00',kind:'cron',cron:'0 17 * * 1-5',prompt:'检查当前项目自上一个工作日同一计划时刻至本次执行时间的代码变更，周一覆盖周末。关注正确性、权限校验、数据兼容和测试缺口；按影响程度整理可证实的问题，附文件位置、触发条件和建议。只提出建议，不自动修改代码或提交。没有确认的问题时明确说明。将结果保留在本次会话。'},
  {id:'release-check',name:'每周发布准备检查',label:'周五 15:00',kind:'weekly',weekday:'5',time:'15:00',prompt:'检查当前项目下一次发布的准备情况。优先读取项目已记录的发布计划、目标版本和基线；缺失时明确列为待确认，不自行假定发布范围。结合可访问的变更、测试结果和文档，列出候选发布说明、阻塞项、迁移与回滚检查清单。不要执行发布。将检查报告保留在本次会话。'}
];
function scheduleTemplatePicker(){return `<div class="formfield schedule-template-picker"><label for="task-schedule-template">常用模板 · 可选</label><div class="between rowgap"><select id="task-schedule-template"><option value="">自定义 · 从空白开始</option>${scheduleTemplates.map(t=>`<option value="${t.id}">${t.name} · ${t.label}</option>`).join('')}</select>${button('使用模板','apply-schedule-template','sm')}</div><small>应用会替换周期和提示词；保留项目、模型、权限和时区。所有内容均可继续修改。</small></div>`}
function applyScheduleTemplate(){
  const template=scheduleTemplates.find(t=>t.id===document.querySelector('#task-schedule-template')?.value);
  if(!template){toast('请选择一个常用模板');return}
  const name=document.querySelector('#task-name');
  if(!name.value.trim()||name.value===name.dataset.templateName){name.value=template.name;name.dataset.templateName=template.name}
  document.querySelector('#task-schedule-kind').value=template.kind;
  document.querySelector('#task-schedule-rule-fields').innerHTML=taskScheduleRuleFields(template);
  document.querySelector('#task-schedule-prompt').value=template.prompt+'\n仓库分析先获取任务所选远程分支的最新提交记录，记录统计起止时间、分支、提交依据和获取时间；获取失败明确报告，不把旧数据当作最新。只更新远程记录，不自动合并或覆盖任务工作区。\n以所选时区解释时间范围；仅使用当前项目可访问的数据，注明缺失数据与统计限制，不编造结果。';
  toast('已填入模板，可修改后再创建任务');
}
document.addEventListener('click',event=>{if(event.target.closest('[data-action="apply-schedule-template"]')){event.preventDefault();applyScheduleTemplate()}});
const permissionNames={read:'只读',default:'默认权限',auto:'自动执行'};
function scheduleProject(id){return state.projects.find(p=>p.id===id)}
function scheduleTask(s){return state.tasks[s.taskIndex]}
function scheduleModel(s){return `${state.providers[s.provider]?.name||'Provider 不可用'} / ${s.model}`}
function scheduleRule(s){if(s.kind==='once')return `${s.date||'2026-09-22'} ${s.time}`;if(s.kind==='daily')return `每天 ${s.time}`;if(s.kind==='weekly')return `每周${['日','一','二','三','四','五','六'][+s.weekday]} ${s.time}`;return s.cron||'未设置'}
function scheduleStatusClass(status){return status==='成功'?'live':status==='运行中'||status==='待确认'?'warn':status==='失败'?'danger':''}

function schedulesPage(){
  const rows=state.schedules.filter(s=>state.scheduleFilter==='all'||(state.scheduleFilter==='active'?s.enabled:!s.enabled));
  const next=state.schedules.find(s=>s.enabled)?.next||'暂无';
  return `<div class="page schedule-page"><div class="between rowgap"><div><div class="view-label">SCHEDULED TASKS</div><h1>定时任务</h1></div>${button('新建定时任务','new-schedule','primary','plus')}</div><p class="page-intro">定时任务拥有固定工作区；每次触发在任务内新建 Agent 会话并发送预设提示词。</p><div class="schedule-summary"><div><small>已启用</small><strong>${state.schedules.filter(s=>s.enabled).length}</strong></div><div><small>最近执行</small><strong>${state.scheduleRuns[0]?.status||'暂无'}</strong></div><div><small>下次触发</small><strong>${esc(next)}</strong></div></div><div class="between schedule-toolbar"><div class="segmented">${[['all','全部'],['active','已启用'],['paused','已暂停']].map(([key,label])=>`<button class="${state.scheduleFilter===key?'active':''}" data-action="schedule-filter:${key}">${label}</button>`).join('')}</div><small>时区按每个定时任务保存</small></div><div class="schedule-list">${rows.map(scheduleRow).join('')||'<div class="empty">当前筛选下没有定时任务。</div>'}</div><div class="between schedule-history-heading"><div><h2>执行记录</h2><small>打开历史会话后可以继续对话</small></div><span class="badge">最近 ${state.scheduleRuns.length} 次</span></div><div class="table-wrap"><table class="table schedule-history"><tr><th>开始时间</th><th>定时任务</th><th>结果</th><th>详情</th><th></th></tr>${state.scheduleRuns.map(runRow).join('')}</table></div><div class="note">原型不会注册系统计划、后台唤醒应用或调用模型。设备关机或 PiDock 未运行时不补跑已错过的触发。</div></div>`;
}

function scheduleRow(s){const i=state.schedules.indexOf(s),project=scheduleProject(s.projectId),t=scheduleTask(s),invalid=!t||!state.providers[s.provider]?.enabled||!state.providers[s.provider]?.models.includes(s.model);return `<article class="schedule-row"><div class="schedule-time"><span>${icon('clock')}</span><strong>${esc(scheduleRule(s))}</strong><small>${esc(s.timezone)}</small></div><button class="schedule-main" data-action="edit-schedule:${i}"><span class="between"><strong>${esc(t?.name||s.name)}</strong><span class="badge ${invalid?'danger':s.enabled?'live':''}">${invalid?'配置失效':s.enabled?'已启用':'已暂停'}</span></span><small>${esc(project?.name||'项目不可用')} · ${esc(scheduleModel(s))}</small><p>${esc(s.prompt)}</p><small>${t?.sessions.length||0} 个会话 · 权限：${permissionNames[s.permission]} · 下次：${esc(s.next)}</small></button><div class="schedule-actions"><label class="switch-control" title="${s.enabled?'暂停':'启用'} ${esc(s.name)}"><input type="checkbox" data-schedule-toggle="${i}" ${s.enabled?'checked':''}><span></span></label>${button('查看任务','open-scheduled-task:'+s.taskIndex,'sm')}${button('立即运行','run-schedule:'+i,'sm', 'play')}<button class="iconbtn" data-action="edit-schedule:${i}" title="编辑" aria-label="编辑 ${esc(s.name)}">${icon('settings')}</button></div></article>`}
function runRow(run){const schedule=state.schedules.find(s=>s.id===run.scheduleId);return `<tr><td>${esc(run.started)}</td><td>${esc(schedule?.name||'已删除的定时任务')}</td><td><span class="badge ${scheduleStatusClass(run.status)}">${esc(run.status)}</span></td><td>${esc(run.detail)}</td><td>${run.taskIndex!==null?button('打开会话','open-schedule-run:'+run.taskIndex+':'+run.sessionIndex,'sm'):''}</td></tr>`}

function scheduleDialog(index){
  const s=state.schedules[index],t=s&&scheduleTask(s),project=s&&scheduleProject(s.projectId);if(!s||!t){toast('请从新建任务选择定时任务类型');return}
  modal('编辑定时任务',`<div class="schedule-editor"><div class="grid2"><div class="formfield"><label>项目</label><input value="${esc(project?.name||'项目不可用')}" disabled><input id="schedule-project" type="hidden" value="${esc(s.projectId)}"></div><div class="formfield"><label>任务</label><input id="schedule-name" value="${esc(t.name)}" disabled></div></div><div class="formfield"><label for="schedule-model">Provider / 模型</label><select id="schedule-model">${state.providers.flatMap((p,pi)=>p.models.map(m=>`<option value="${pi}:${esc(m)}" ${pi===s.provider&&m===s.model?'selected':''} ${p.enabled?'':'disabled'}>${esc(p.name)} / ${esc(modelDetail(p,m).name)}</option>`)).join('')}</select></div><div class="grid2"><div class="formfield"><label for="schedule-kind">执行周期</label><select id="schedule-kind">${Object.entries(scheduleKinds).map(([key,label])=>`<option value="${key}" ${key===s.kind?'selected':''}>${label}</option>`).join('')}</select></div><div class="formfield"><label for="schedule-timezone">时区</label><select id="schedule-timezone"><option ${s.timezone==='Asia/Shanghai'?'selected':''}>Asia/Shanghai</option><option ${s.timezone==='UTC'?'selected':''}>UTC</option><option ${s.timezone==='America/Los_Angeles'?'selected':''}>America/Los_Angeles</option></select></div></div><div id="schedule-rule-fields">${scheduleRuleFields(s)}</div><div class="formfield"><label for="schedule-permission">新会话权限</label><select id="schedule-permission"><option value="read" ${s.permission==='read'?'selected':''}>只读</option><option value="default" ${s.permission==='default'?'selected':''}>默认权限 · 需要时等待确认</option><option value="auto" ${s.permission==='auto'?'selected':''}>自动执行 · 仍受任务边界约束</option></select></div><div class="formfield"><label for="schedule-prompt">提示词</label><textarea id="schedule-prompt" rows="6" placeholder="包括要处理的内容，以及如何保存、发送或使用结果">${esc(s.prompt)}</textarea><small>结果的保存、通知或发送方式写在提示词中，并受会话权限与可用工具约束。</small></div><div class="schedule-policy"><strong>每次触发</strong><span>在当前任务中创建新的独立会话</span><span>历史会话可查看并继续对话</span><span>上一次仍在运行时跳过本次</span></div></div>`,button('保存更改','save-schedule:'+index,'primary'));
  document.querySelector('.modal').classList.add('schedule-editor-modal');
}
function scheduleRuleFields(s){if(s.kind==='once')return `<div class="grid2"><div class="formfield"><label for="schedule-date">日期</label><input id="schedule-date" type="date" value="${esc(s.date||'2026-09-22')}"></div><div class="formfield"><label for="schedule-time">时间</label><input id="schedule-time" type="time" value="${esc(s.time)}"></div></div>`;if(s.kind==='weekly')return `<div class="grid2"><div class="formfield"><label for="schedule-weekday">星期</label><select id="schedule-weekday">${['星期日','星期一','星期二','星期三','星期四','星期五','星期六'].map((d,i)=>`<option value="${i}" ${String(i)===String(s.weekday)?'selected':''}>${d}</option>`).join('')}</select></div><div class="formfield"><label for="schedule-time">时间</label><input id="schedule-time" type="time" value="${esc(s.time)}"></div></div>`;if(s.kind==='cron')return `<div class="formfield"><label for="schedule-cron">Cron 表达式</label><input id="schedule-cron" class="mono" value="${esc(s.cron||'0 9 * * 1-5')}" placeholder="分钟 小时 日 月 星期"><small>按所选时区解释，使用五段格式。</small></div>`;return `<div class="formfield"><label for="schedule-time">时间</label><input id="schedule-time" type="time" value="${esc(s.time)}"></div>`}
function currentScheduleDraft(){const model=document.querySelector('#schedule-model').value.split(':');return {name:document.querySelector('#schedule-name').value.trim(),projectId:document.querySelector('#schedule-project').value,provider:+model.shift(),model:model.join(':'),prompt:document.querySelector('#schedule-prompt').value.trim(),kind:document.querySelector('#schedule-kind').value,date:document.querySelector('#schedule-date')?.value||'',time:document.querySelector('#schedule-time')?.value||'',weekday:document.querySelector('#schedule-weekday')?.value||'1',cron:document.querySelector('#schedule-cron')?.value.trim()||'',timezone:document.querySelector('#schedule-timezone').value,permission:document.querySelector('#schedule-permission').value,enabled:true}}
function nextScheduleLabel(s){if(s.kind==='once')return `${s.date} ${s.time}`;if(s.kind==='daily')return `明天 ${s.time}`;if(s.kind==='weekly')return `下周${['日','一','二','三','四','五','六'][+s.weekday]} ${s.time}`;return '按自定义周期'}

function taskTypePicker(selected='normal'){return `<div class="task-type-picker"><label>任务类型</label><div class="segmented"><label><input type="radio" name="task-type" value="normal" ${selected==='normal'?'checked':''}><span>${icon('chat')}普通任务</span></label><label><input type="radio" name="task-type" value="scheduled" ${selected==='scheduled'?'checked':''}><span>${icon('clock')}定时任务</span></label></div></div>`}
function taskScheduleRuleFields(s){if(s.kind==='once')return `<div class="grid2"><div class="formfield"><label for="task-schedule-date">日期</label><input id="task-schedule-date" type="date" value="${esc(s.date||'2026-09-22')}"></div><div class="formfield"><label for="task-schedule-time">时间</label><input id="task-schedule-time" type="time" value="${esc(s.time||'09:30')}"></div></div>`;if(s.kind==='weekly')return `<div class="grid2"><div class="formfield"><label for="task-schedule-weekday">星期</label><select id="task-schedule-weekday">${['星期日','星期一','星期二','星期三','星期四','星期五','星期六'].map((d,i)=>`<option value="${i}" ${String(i)===String(s.weekday)?'selected':''}>${d}</option>`).join('')}</select></div><div class="formfield"><label for="task-schedule-time">时间</label><input id="task-schedule-time" type="time" value="${esc(s.time||'09:30')}"></div></div>`;if(s.kind==='cron')return `<div class="formfield"><label for="task-schedule-cron">Cron 表达式</label><input id="task-schedule-cron" class="mono" value="${esc(s.cron||'15 9 * * 1-5')}" placeholder="分钟 小时 日 月 星期"></div>`;return `<div class="formfield"><label for="task-schedule-time">时间</label><input id="task-schedule-time" type="time" value="${esc(s.time||'09:30')}"></div>`}
function scheduledTaskFields(s={kind:'daily',time:'09:30',weekday:'1',cron:'15 9 * * 1-5',timezone:'Asia/Shanghai',provider:0,model:state.providers[0]?.models[0]||'',permission:'default',prompt:''}){return `<section class="new-task-schedule-fields"><h3>定时设置</h3>${scheduleTemplatePicker()}<div class="grid2"><div class="formfield"><label for="task-schedule-model">Provider / 模型</label><select id="task-schedule-model">${state.providers.flatMap((p,pi)=>p.models.map(m=>`<option value="${pi}:${esc(m)}" ${pi===s.provider&&m===s.model?'selected':''} ${p.enabled?'':'disabled'}>${esc(p.name)} / ${esc(modelDetail(p,m).name)}</option>`)).join('')}</select></div><div class="formfield"><label for="task-schedule-permission">新会话权限</label><select id="task-schedule-permission"><option value="read" ${s.permission==='read'?'selected':''}>只读</option><option value="default" ${s.permission==='default'?'selected':''}>默认权限 · 需要时等待确认</option><option value="auto" ${s.permission==='auto'?'selected':''}>自动执行</option></select></div></div><div class="grid2"><div class="formfield"><label for="task-schedule-kind">执行周期</label><select id="task-schedule-kind">${Object.entries(scheduleKinds).map(([key,label])=>`<option value="${key}" ${key===s.kind?'selected':''}>${label}</option>`).join('')}</select></div><div class="formfield"><label for="task-schedule-timezone">时区</label><select id="task-schedule-timezone"><option selected>Asia/Shanghai</option><option>UTC</option><option>America/Los_Angeles</option></select></div></div><div id="task-schedule-rule-fields">${taskScheduleRuleFields(s)}</div><div class="formfield"><label for="task-schedule-prompt">提示词</label><textarea id="task-schedule-prompt" rows="5" placeholder="包括要处理的内容，以及如何保存、发送或使用结果">${esc(s.prompt)}</textarea><small>每次触发新建一个可查看、可继续对话的独立会话。</small></div></section>`}
function readScheduledTaskDraft(){const model=document.querySelector('#task-schedule-model').value.split(':');return {provider:+model.shift(),model:model.join(':'),permission:document.querySelector('#task-schedule-permission').value,kind:document.querySelector('#task-schedule-kind').value,date:document.querySelector('#task-schedule-date')?.value||'',time:document.querySelector('#task-schedule-time')?.value||'',weekday:document.querySelector('#task-schedule-weekday')?.value||'1',cron:document.querySelector('#task-schedule-cron')?.value.trim()||'',timezone:document.querySelector('#task-schedule-timezone').value,prompt:document.querySelector('#task-schedule-prompt').value.trim()}}
function validateScheduledTaskDraft(s){if(!s.model||!s.prompt){toast('定时任务需要选择模型并填写提示词');return false}if(s.kind!=='cron'&&!s.time){toast('请选择执行时间');return false}if(s.kind==='once'&&!s.date){toast('请选择执行日期');return false}if(s.kind==='cron'&&s.cron.split(/\s+/).length!==5){toast('Cron 表达式需要五段');return false}return true}
function attachScheduleToTask(t,taskIndex,draft){const id=crypto.randomUUID(),schedule={...draft,id,name:t.name,projectId:t.projectId,taskIndex,enabled:true,last:'尚未执行'};schedule.next=nextScheduleLabel(schedule);t.taskType='scheduled';t.scheduleId=id;t.sessions=['等待首次执行'];t.session=0;t.sessionData={0:{draft:'',refs:[],provider:draft.provider,model:draft.model,context:0,tokens:0}};t.messages=[];t.permissionsBySession={0:draft.permission};state.schedules.unshift(schedule)}
function saveSchedule(index){const draft=currentScheduleDraft(),s=state.schedules[+index];if(!s||!draft.model||!draft.prompt){toast('请填写模型和提示词');return}if(draft.kind!=='cron'&&!draft.time){toast('请选择执行时间');return}if(draft.kind==='once'&&!draft.date){toast('请选择执行日期');return}if(draft.kind==='cron'&&draft.cron.trim().split(/\s+/).length!==5){toast('Cron 表达式需要五段');return}Object.assign(s,draft,{id:s.id,name:s.name,taskIndex:s.taskIndex,last:s.last,enabled:s.enabled,next:nextScheduleLabel(draft)});closeModal();render();toast('已保存模拟定时任务')}
function runSchedule(index){const s=state.schedules[index],t=s&&scheduleTask(s),provider=s&&state.providers[s.provider];if(!t){toast('关联任务已不存在，请先处理定时任务');return}if(!provider?.enabled||!provider.models.includes(s.model)){toast('Provider 或模型不可用，请先修改定时任务');return}if(state.scheduleRuns.some(r=>r.scheduleId===s.id&&r.status==='运行中')){toast('上一次执行仍在运行，本次已跳过');return}const sessionIndex=t.sessions.length,label='刚刚 · 定时执行';t.sessions.push(label);t.session=sessionIndex;t.sessionData[sessionIndex]={draft:'',refs:[],provider:s.provider,model:s.model,context:0,tokens:0};t.permissionsBySession??={};t.permissionsBySession[sessionIndex]=s.permission;t.messages.push({role:'user',text:s.prompt,permission:s.permission,session:sessionIndex},{role:'agent',text:'定时任务已触发。这是模拟会话，未调用真实模型、Git 工具或消息连接器；可以在此继续对话。',session:sessionIndex});t.isNew=true;state.scheduleRuns.unshift({id:crypto.randomUUID(),scheduleId:s.id,started:'刚刚',status:'运行中',detail:'已在任务中创建新会话',taskIndex:s.taskIndex,sessionIndex});s.last='刚刚 · 运行中';render();toast('已模拟在定时任务中创建 Agent 会话')}

function openScheduledSession(taskIndex,sessionIndex){const t=state.tasks[taskIndex];if(!t){toast('关联任务不在当前页面内存中');return}state.task=taskIndex;state.projectId=t.projectId;state.envId=t.envId;state.env=t.env;t.session=Math.min(Number.isFinite(sessionIndex)?sessionIndex:t.session,t.sessions.length-1);state.view='task';render()}
function scheduleAction(a,arg){if(a==='new-schedule'){taskDialog(false,'scheduled');return true}if(a==='edit-schedule'){scheduleDialog(+arg);return true}if(a==='save-schedule'){saveSchedule(arg);return true}if(a==='schedule-filter'){state.scheduleFilter=arg;render();return true}if(a==='run-schedule'){runSchedule(+arg);return true}if(a==='open-scheduled-task'){openScheduledSession(+arg,0);return true}if(a==='open-schedule-run'){const [taskIndex,sessionIndex]=arg.split(':').map(Number);openScheduledSession(taskIndex,sessionIndex);return true}return false}
document.addEventListener('click',event=>{const target=event.target.closest('[data-action]');if(!target)return;const [action,...rest]=target.dataset.action.split(':');if(scheduleAction(action,rest.join(':'))){event.preventDefault();event.stopImmediatePropagation()}});
document.addEventListener('change',event=>{if(event.target.dataset.scheduleToggle!==undefined){const s=state.schedules[+event.target.dataset.scheduleToggle];s.enabled=event.target.checked;s.next=s.enabled?nextScheduleLabel(s):'已暂停';render();toast(s.enabled?'已启用模拟定时任务':'已暂停模拟定时任务')}if(event.target.id==='schedule-kind'){const current=currentScheduleDraft();document.querySelector('#schedule-rule-fields').innerHTML=scheduleRuleFields({...current,time:current.time||'09:30',date:current.date||'2026-09-22',weekday:current.weekday||'1',cron:current.cron||'0 9 * * 1-5'})}if(event.target.name==='task-type'){document.querySelector('#new-task-schedule').innerHTML=event.target.value==='scheduled'?scheduledTaskFields():''}if(event.target.id==='task-schedule-kind'){const current=readScheduledTaskDraft();document.querySelector('#task-schedule-rule-fields').innerHTML=taskScheduleRuleFields({...current,time:current.time||'09:30',date:current.date||'2026-09-22',weekday:current.weekday||'1',cron:current.cron||'15 9 * * 1-5'})}});
