/* THROWAWAY — illustrative child-agent records; no agents are launched. */
function initializeSubagents(){
 state.tasks[0].subagentsBySession={0:[
  {id:'query-chain',name:'查询链路分析',status:'running',summary:'正在核对 BFF 到 invoice、shipment 的调用关系',assignment:'梳理对账单详情查询链路，确认运单账号字段来源。只读检查，不修改文件；将关键文件和结论交回主 Agent。',model:'Claude Sonnet',provider:'Anthropic · 工作账号',started:'10:25',mode:'只读分析',events:[
   {kind:'message',role:'主 Agent',time:'10:25',text:'请检查 invoice-service 与 shipment-service 中对账单详情的同步查询，列出运单账号的数据来源和相关文件。'},
   {kind:'message',role:'Subagent',time:'10:25',text:'已接收任务，将从详情接口和 shipment 查询入口检查字段传递。'},
   {kind:'tool',name:'搜索调用入口',time:'10:26',command:'search · invoice-service / shipment-service',output:'示例匹配：\ninvoice-service/internal/service/detail.go\nshipment-service/internal/service/shipment.go\n发现详情查询及 shipment 查询入口。'},
   {kind:'message',role:'Subagent',time:'10:26',text:'已找到 invoice 到 shipment 的同步调用。正在核对账号字段缺失时的返回行为。'}]},
  {id:'ui-field',name:'前端字段检查',status:'completed',summary:'已完成：确认详情页字段映射与空值展示',assignment:'检查前端对账单详情中运单账号的展示与空值处理。只读分析，将发现回传主 Agent。',model:'Claude Sonnet',provider:'Anthropic · 工作账号',started:'10:25',mode:'只读分析',events:[
   {kind:'message',role:'主 Agent',time:'10:25',text:'请检查 front-monorepo 的详情字段映射和空值展示，不修改代码。'},
   {kind:'tool',name:'读取详情组件',time:'10:26',command:'read · front-monorepo/src/detail.ts',output:'示例片段：\naccount: response.account\n展示层在字段为空时显示占位符。'},
   {kind:'message',role:'Subagent',time:'10:27',text:'检查完成：详情页直接读取 account 字段，空值会显示占位符。建议主 Agent 结合后端字段来源确认是否需要补充映射，再统一修改。'}],result:'已向主 Agent 返回：前端直接读取 account；需要结合后端响应确认空值处理。'}
 ]};
 state.tasks[1].subagentsBySession={0:[{id:'address-rules',name:'地址规则检查',status:'completed',summary:'已完成：整理地址必填项',assignment:'只读梳理运单地址校验规则，将必填项与边界条件返回主 Agent。',model:'Claude Sonnet',provider:'Anthropic · 工作账号',started:'10:18',mode:'只读分析',events:[{kind:'message',role:'主 Agent',time:'10:18',text:'请整理运单地址的必填字段和校验边界。'},{kind:'message',role:'Subagent',time:'10:20',text:'已整理联系人、电话、省市区与详细地址的必填规则，结果已交回主 Agent。'}],result:'地址必填项与边界条件已整理。'}]};
}
function sessionSubagents(){return task()?.subagentsBySession?.[task().session]||[]}
function subagentStatus(agent){return {running:'运行中',completed:'已完成',waiting:'等待中',failed:'失败',stopped:'已停止'}[agent.status]||'状态未知'}
function selectedSubagent(){const agents=sessionSubagents();const selected=task()?.selectedSubagentIds?.[task().session];return agents.find(a=>a.id===selected)||agents[0]}
function subagentButton(){const count=sessionSubagents().length;return `<button class="iconbtn ${task().subagentPanelOpen?'selected':''}" data-action="subagents" aria-label="查看 Subagent${count?'，共 '+count+' 个':''}" title="查看当前会话的 Subagent">${icon('branch')}</button>`}
function sessionSubagentList(){const agents=sessionSubagents();if(!agents.length)return '';const running=agents.filter(a=>a.status==='running').length;return `<div class="session-subagents" aria-label="当前会话启动的 Subagent"><div class="between"><span class="subagent-list-label">${icon('branch')} Subagent <span class="badge">${agents.length}</span></span><small>${running?running+' 个运行中':'全部已结束'} · 示例</small></div><div class="subagent-cards">${agents.map(a=>`<button class="subagent-card ${task().subagentPanelOpen&&selectedSubagent()?.id===a.id?'selected':''}" data-action="select-subagent:${a.id}" aria-label="查看 ${esc(a.name)}，${subagentStatus(a)}" aria-pressed="${task().subagentPanelOpen&&selectedSubagent()?.id===a.id?'true':'false'}"><div class="between"><strong>${esc(a.name)}</strong><span class="subagent-status ${a.status}"><span class="dot ${a.status==='running'?'live':''}"></span>${subagentStatus(a)}</span></div><small>${esc(a.summary)}</small></button>`).join('')}</div></div>`}
function subagentSidebar(){const agent=selectedSubagent();return `<aside class="subagent-sidebar" aria-label="Subagent 内容"><div class="subagent-panel-header between"><span class="flex">${icon('branch')}<strong>Subagent</strong><span class="badge">示例记录</span></span><button class="iconbtn" data-action="close-subagents" aria-label="关闭 Subagent 侧栏" title="关闭侧栏">${icon('close')}</button></div><div class="subagent-parent"><small>${esc(currentProject().name)} / ${esc(task().name)}</small><span>所属会话：${esc(task().sessions[task().session])}</span></div>${agent?`<div class="subagent-identity"><label class="subagent-select-label" for="subagent-select">选择 Subagent</label><select id="subagent-select">${sessionSubagents().map(a=>`<option value="${a.id}" ${a.id===agent.id?'selected':''}>${esc(a.name)} · ${subagentStatus(a)}</option>`).join('')}</select><div class="between"><span class="subagent-status ${agent.status}"><span class="dot ${agent.status==='running'?'live':''}"></span>${subagentStatus(agent)}</span><small>${agent.started} 启动 · ${esc(agent.mode)}</small></div><small>${esc(agent.provider)} / ${esc(agent.model)}</small></div><div class="subagent-transcript"><details class="subagent-assignment"><summary>分配的任务</summary><p>${esc(agent.assignment)}</p></details>${agent.events.map(e=>e.kind==='tool'?`<details class="subagent-tool"><summary><span>${icon('terminal')} ${esc(e.name)}</span><small>${e.time}</small></summary><code>${esc(e.command)}</code><pre>${esc(e.output)}</pre></details>`:`<article class="subagent-message"><div class="between"><strong>${e.role==='主 Agent'?'主 Agent':esc(agent.name)}</strong><small>${e.time}</small></div><p>${esc(e.text)}</p></article>`).join('')}${agent.status==='running'?'<div class="subagent-live-note"><span class="dot live"></span> 示例：等待下一条输出</div>':''}${agent.result?`<div class="subagent-result"><strong>${icon('check')} 已返回主会话</strong><p>${esc(agent.result)}</p></div>`:''}</div><div class="subagent-readonly">仅查看 · 左侧输入框仍发送给主会话</div>`:'<div class="subagent-empty"><span class="subagent-empty-icon">'+icon('branch')+'</span><h3>本会话尚未启动 Subagent</h3><p>启动后会在这里展示它的任务、状态和执行内容。</p></div>'}</aside>`}
function subagentWorkspace(){return `<div class="subagent-workspace">${conversation()}${subagentSidebar()}</div>`}
function subagentAction(action,arg){if(action==='subagents'||action==='select-subagent'){const agent=sessionSubagents().find(a=>a.id===arg)||selectedSubagent();task().selectedSubagentIds??={};if(agent)task().selectedSubagentIds[task().session]=agent.id;task().subagentPanelOpen=true;render();return true}if(action==='close-subagents'){task().subagentPanelOpen=false;render();return true}return false}
